language: python
sudo: required
python:
#- "3.2" # C:\Python32\lib\site-packages\pkg_resources\__init__.py:80: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
# install the package
- PACKAGE_VERSION=`python setup.py --version`
- TAG_NAME=v$PACKAGE_VERSION
# install from the zip file to see if files were forgotten
- python setup.py sdist --dist-dir=dist --formats=zip
- pip install wheel
- ( cd dist ; pip install crc8-${PACKAGE_VERSION}.zip )
before_script:
# remove the build folder because it creates problems for py.test
- rm -rf build
# show the versions
- python setup.py --version
- py.test --version
- echo Package version $PACKAGE_VERSION with possible tag name $TAG_NAME
script:
- python test_crc8.py
# test import form everywhere
- ( cd / && python -c "import crc8;print(\"imported\")" )
# run tests from installation
- mkdir x ; cp test_crc8.py x ; ( cd x ; python test_crc8.py )
# test that the tag represents the version
# https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
- ( if [ -n "$TRAVIS_TAG" ]; then if [ $TAG_NAME != $TRAVIS_TAG ]; then echo "This tag is for the wrong version. Got \"$TRAVIS_TAG\" expected \"$TAG_NAME\"."; exit 1; fi; fi; )
before_deploy:
# create the documentation
- python setup.py sdist bdist_wheel
deploy:
# created with travis command line tool
# https://docs.travis-ci.com/user/deployment/pypi
# $ travis setup pypi
  provider: pypi
  user: niccokunzmann2
  password:
    secure: ZznEO5CaG0xDaIUQ5BNNJO+nVncpz0GvGInAdkjq/3p+yVUupLhWZNFGZiO7DhKnjJPd2FKtczSbLtauLvxQXY6PCzU8mCDthNjqatumIwbWYDuMiTrlG0SaBarvmtnidQ8z08lvF2VJuEVOO2MAF6XxA3t9tnflhhofOJiScNMKWS9MK0YeYWR7Hz8wDKei6Mn3YGZxyJ5U2AMrCtnHhDXP7DlWkGrmmPBB2Axh6sqoj2FMvfb3Ki7BwSWLJnW6dOcZ7OrfWGTOYlnxG57KDr/UW9j9Di8qc6dDX4+qZgh2C1XwvBxlekvY4CoeYVXVj94GKmty1m0Zz+WD/hT1LYJ+/4PUVuKWB/T9W8LIQ93A/WNini/UA7Cg9TtMG53D+PNueTbNhw7/VwDK8EFzzGY1+d54wgNVt2dwfShmxKD80UZalFBuAJIRifO+NZ+1yHStSRsb2LsIRS4cif3DXky4syy3ZX48enEuMk2n4+fvN493y+4CjAZHUkk3ow8Iu60pfyFANKn9NHnj7XzMmpx7z70AvizBevpc10ziIFBX8ao6npf32f1GUpVOiDLjP4TBpchK0WzeDd+bB51lUgZOFDjtkfoddPcDrq2YeZJ3KH0duaQHbOuFvX3QB/kIS5y71xxAlwmLHM4RlVYRVbRF3GktckeqhVknsaoYoac=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: niccokunzmann/crc8
